# Concat

In [4]:
from pandas import DataFrame
import pandas as pd

# 첫번째 데이터프레임
data = {
    '종가': [113000, 111500],
    '거래량': [555850, 282163]
}
index = ["2019-06-21", "2019-06-20"]
df1 = DataFrame(data, index=index)
df1

                종가     거래량
2019-06-21  113000  555850
2019-06-20  111500  282163

In [3]:
# 두번째 데이터프레임
data = {
    '종가': [110000, 483689],
    '거래량': [109000, 791946]
}
index = ["2019-06-19", "2019-06-18"]

df2 =DataFrame(data, index=index)
df2

                종가     거래량
2019-06-19  110000  109000
2019-06-18  483689  791946

In [6]:
result = pd.concat([df2,df1])
result

                종가     거래량
2019-06-19  110000  109000
2019-06-18  483689  791946
2019-06-21  113000  555850
2019-06-20  111500  282163

# Merge

In [14]:
from pandas import DataFrame
import pandas as pd

# 첫 번째 데이터프레임
data = [
    ["전기전자", "005930", "삼성전자", 74400],
    ["화학", "051910", "LG화학", 896000],
    ["전기전자", "000660", "SK하이닉스", 101500]
]

columns = ["업종", "종목코드", "종목명", "현재가"]
df1 = DataFrame(data=data, columns=columns)

In [13]:
# 두 번째 데이터프레임
data = [
    ["은행", 2.92],
    ["보험", 0.37],
    ["화학", 0.06],
    ["전기전자", -2.43]
]

columns = ["업종", "등락률"]
df2 = DataFrame(data=data, columns=columns)

In [10]:
df1

     업종    종목코드     종목명     현재가
0  전기전자  005930    삼성전자   74400
1    화학  051910    LG화학  896000
2  전기전자  000660  SK하이닉스  101500

In [11]:
df2

     업종   등락률
0    은행  2.92
1    보험  0.37
2    화학  0.06
3  전기전자 -2.43

In [12]:
pd.merge(left = df1, right = df2, on = '업종')

     업종    종목코드     종목명     현재가   등락률
0  전기전자  005930    삼성전자   74400 -2.43
1    화학  051910    LG화학  896000  0.06
2  전기전자  000660  SK하이닉스  101500 -2.43

In [17]:
from pandas import DataFrame
import pandas as pd

# 첫 번째 데이터프레임
data = [
    ["전기전자", "005930", "삼성전자", 74400],
    ["화학", "051910", "LG화학", 896000],
    ["서비스업", "035720", "카카오", 101500]
]

columns = ["업종", "종목코드", "종목명", "현재가"]
df1 = DataFrame(data=data, columns=columns)

df1

     업종    종목코드   종목명     현재가
0  전기전자  005930  삼성전자   74400
1    화학  051910  LG화학  896000
2  서비스업  035720   카카오  101500

In [19]:
# 두 번째 데이터프레임
data = [
    ["은행", 2.92],
    ["보험", 0.37],
    ["화학", 0.06],
    ["전기전자", -2.43]
]

columns = ["업종", "등락률"]
df2 = DataFrame(data=data, columns=columns)
df2

     업종   등락률
0    은행  2.92
1    보험  0.37
2    화학  0.06
3  전기전자 -2.43

In [27]:
#df = pd.merge(left = df1, right = df2 , how='outer',on= '업종') # 왼쪽 테이블은 무조건 나오게 만들어서 NAN 이 나옴 키값이 없어서
#df

In [34]:
# 첫 번째 데이터프레임
data = [
    ["전기전자", "005930", "삼성전자", 74400],
    ["화학", "051910", "LG화학", 896000],
    ["서비스업", "035720", "카카오", 101500]
]

columns = ["업종", "종목코드", "종목명", "현재가"]
df1 = DataFrame(data=data, columns=columns)

# 두 번째 데이터프레임
data = [
    ["은행", 2.92],
    ["보험", 0.37],
    ["화학", 0.06],
    ["전기전자", -2.43]
]

columns = ["항목", "등락률"]
df2 = DataFrame(data=data, columns=columns)

df = pd.merge(left = df1, right = df2 , how='left', left_on='업종',right_on ='항목') 
df

     업종    종목코드   종목명     현재가    항목   등락률
0  전기전자  005930  삼성전자   74400  전기전자 -2.43
1    화학  051910  LG화학  896000    화학  0.06
2  서비스업  035720   카카오  101500   NaN   NaN

# join

In [35]:
data = [
    ["전기전자", "005930", "삼성전자", 74400],
    ["화학", "051910", "LG화학", 896000],
    ["서비스업", "035720", "카카오", 101500]
]

columns = ["업종", "종목코드", "종목명", "현재가"]
df1 = DataFrame(data=data, columns=columns)
df1= df1.set_index("업종")
print(df1)

# 두 번째 데이터프레임
data = [
    ["은행", 2.92],
    ["보험", 0.37],
    ["화학", 0.06],
    ["전기전자", -2.43]
]

columns = ["항목", "등락률"]
df2 = DataFrame(data=data, columns=columns)
df2 = df2.set_index("항목")
print(df2)

        종목코드   종목명     현재가
업종
전기전자  005930  삼성전자   74400
화학    051910  LG화학  896000
서비스업  035720   카카오  101500
       등락률
항목
은행    2.92
보험    0.37
화학    0.06
전기전자 -2.43

In [36]:
# merge = 기본값 : inner_join 
# join = 기본값 : left_join
# how를 써서 명시적으로 표현하는게 났다.
df1.join(other=df2, how = "inner")

        종목코드   종목명     현재가   등락률
업종
전기전자  005930  삼성전자   74400 -2.43
화학    051910  LG화학  896000  0.06
서비스업  035720   카카오  101500   NaN

# 연도별로 그룹바이 연산 , 시가총액 평균을 구하자

In [47]:
data = [
    ["2017", "삼성", 500],
    ["2017", "LG", 300],    
    ["2017", "SK하이닉스", 200],
    ["2018", "삼성", 600],
    ["2018", "LG", 400],
    ["2018", "SK하이닉스", 300],    
]

columns = ["연도", "회사", "시가총액"]
df = DataFrame(data=data, columns=columns)
df

     연도      회사  시가총액
0  2017      삼성   500
1  2017      LG   300
2  2017  SK하이닉스   200
3  2018      삼성   600
4  2018      LG   400
5  2018  SK하이닉스   300

In [50]:
result = df.groupby('연도')['시가총액'].mean().to_frame()
result.columns = ['시가총액평균']
result

          시가총액평균
연도
2017  333.333333
2018  433.333333

In [59]:
df = df.join(result, on = '연도')
df

     연도      회사  시가총액    규모      시가총액평균
0  2017      삼성   500   대형주  333.333333
1  2017      LG   300  중소형주  333.333333
2  2017  SK하이닉스   200  중소형주  333.333333
3  2018      삼성   600   대형주  433.333333
4  2018      LG   400   대형주  433.333333
5  2018  SK하이닉스   300  중소형주  433.333333

In [60]:
# 시가총액평균을 기준값으로
# 새로운 컬럼 :규모 
# 대형주 , 중소형주
import numpy as np

#numpy.where 활용해서 series 연산
df ['규모'] = np.where(df['시가총액'] >= df['시가총액평균'],"대형주","중소형주")

     연도      회사  시가총액    규모      시가총액평균
0  2017      삼성   500   대형주  333.333333
1  2017      LG   300  중소형주  333.333333
2  2017  SK하이닉스   200  중소형주  333.333333
3  2018      삼성   600   대형주  433.333333
4  2018      LG   400  중소형주  433.333333
5  2018  SK하이닉스   300  중소형주  433.333333

In [62]:
df.drop('시가총액평균', axis = 1)

     연도      회사  시가총액    규모
0  2017      삼성   500   대형주
1  2017      LG   300  중소형주
2  2017  SK하이닉스   200  중소형주
3  2018      삼성   600   대형주
4  2018      LG   400  중소형주
5  2018  SK하이닉스   300  중소형주

In [55]:
import pandas as pd
import numpy as np

# 시가총액 평균 계산
mean_market_cap = df["시가총액"].mean()

# numpy.where를 사용하여 '규모'라는 새로운 컬럼 추가
df['규모'] = np.where(df['시가총액'] >= mean_market_cap, '대형주', '중소형주')

# 결과 출력
print(df)

     연도      회사  시가총액    규모
0  2017      삼성   500   대형주
1  2017      LG   300  중소형주
2  2017  SK하이닉스   200  중소형주
3  2018      삼성   600   대형주
4  2018      LG   400   대형주
5  2018  SK하이닉스   300  중소형주

## 멀티 인덱스

In [65]:
from pandas import DataFrame
import pandas as pd

data = [
    ["영업이익", "컨센서스", 1000, 1200],
    ["영업이익", "잠정치", 900, 1400],
    ["당기순이익", "컨센서스", 800, 900],
    ["당기순이익", "잠정치", 700, 800]
]

df = DataFrame(data=data)
df = df.set_index([0, 1])
type(df)

pandas.core.frame.DataFrame

In [67]:
df.loc[('영업이익','컨센서스'),:]

2    1000
3    1200
Name: (영업이익, 컨센서스), dtype: int64

In [68]:
df2 = df.reset_index()
df2

       0     1     2     3
0   영업이익  컨센서스  1000  1200
1   영업이익   잠정치   900  1400
2  당기순이익  컨센서스   800   900
3  당기순이익   잠정치   700   800

In [74]:
import seaborn as sns

tips = sns.load_dataset("tips")
result=tips.groupby(['sex','smoker','day'])[['total_bill','tip']].mean()
result.loc[('Male','Yes','Fri'),:][1] # 복잡

C:\Users\campus3S005\AppData\Local\Temp\ipykernel_19108\2698898350.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result=tips.groupby(['sex','smoker','day'])[['total_bill','tip']].mean()
C:\Users\campus3S005\AppData\Local\Temp\ipykernel_19108\2698898350.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  result.loc[('Male','Yes','Fri'),:][1]

np.float64(2.74125)

In [79]:
tips = sns.load_dataset("tips")
result= tips.groupby(['sex','smoker','day'])[['total_bill','tip']].mean().reset_index()
result.loc[result['day'] == 'Fri' , :]

C:\Users\campus3S005\AppData\Local\Temp\ipykernel_19108\1103735758.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result= tips.groupby(['sex','smoker','day'])[['total_bill','tip']].mean().reset_index()

       sex smoker  day  total_bill       tip
1     Male    Yes  Fri   20.452500  2.741250
5     Male     No  Fri   17.475000  2.500000
9   Female    Yes  Fri   12.654286  2.682857
13  Female     No  Fri   19.365000  3.125000

## 멀티 컬럼

In [80]:
from pandas import DataFrame

data = [
    [100, 900, 800, 700],
    [1200, 1400, 900, 800]
]

columns = [
    ['영업이익', '영업이익', '당기순이익', '당기순이익'],
    ['컨센서스', '잠정치', '컨센서스', '잠정치']
]

index = ["2020/06", "2020/09"]

df = DataFrame(data=data, index=index, columns=columns)
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [ ]:
# 멀티 컬럼의 단계를 영업이익은 레벨 1 컨센션스는 레벨 2

In [84]:
level_0 = ["영업이익", "당기순이익"]
level_1 = ["컨센서스", "잠정치"]

idx = pd.MultiIndex.from_product([level_0, level_1])

#데이터 프레임을 다시 만들어야 한다
idx

df = pd.DataFrame(data = data, index = ["2020/06","2020/09"], columns = idx)
df['영업이익']

         컨센서스   잠정치
2020/06   100   900
2020/09  1200  1400